{% set name = "sqls" %}
{% set version = "0.2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sqls-server/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 18dd9a4c35137ed01926638a1fa8b0f54f1dd00af0e8e54e18a257ddd62eae45

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ stdlib('c') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/sqls-server/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: SQL language server written in Go.
  dev_url: https://github.com/sqls-server/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
