context:
  version: "0.2.46"

package:
  name: sqls
  version: ${{ version }}

source:
  url: https://github.com/sqls-server/sqls/archive/v${{ version }}.tar.gz
  sha256: 21ef6db4a0be220b249a90edee3555273c28755b52a25e51e3b798d90326d0c4

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - sqls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: SQL language server written in Go.
  homepage: https://github.com/sqls-server/sqls
  repository: https://github.com/sqls-server/sqls

extra:
  recipe-maintainers:
    - danielnachun
