context:
  version: "0.2.32"

package:
  name: sqls
  version: ${{ version }}

source:
  url: https://github.com/sqls-server/sqls/archive/v${{ version }}.tar.gz
  sha256: a85138e1d459298b00879e31c43a5525faad49b8dc811eb34a5854fab74c7be0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - sqls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: SQL language server written in Go.
  homepage: https://github.com/sqls-server/sqls
  repository: https://github.com/sqls-server/sqls

extra:
  recipe-maintainers:
    - danielnachun
