context:
  version: "0.2.30"

package:
  name: sqls
  version: ${{ version }}

source:
  url: https://github.com/sqls-server/sqls/archive/v${{ version }}.tar.gz
  sha256: 4d8b00b8ead621a418039dab7d2567737902d3ab59b555124b780df47c3615bc

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - sqls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: SQL language server written in Go.
  homepage: https://github.com/sqls-server/sqls
  repository: https://github.com/sqls-server/sqls

extra:
  recipe-maintainers:
    - danielnachun
