context:
  version: "0.2.45"

package:
  name: sqls
  version: ${{ version }}

source:
  url: https://github.com/sqls-server/sqls/archive/v${{ version }}.tar.gz
  sha256: 7fb0914932176cbe875c53a8ebebf4561dd859a8068295c457d50c417f265602

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - sqls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: SQL language server written in Go.
  homepage: https://github.com/sqls-server/sqls
  repository: https://github.com/sqls-server/sqls

extra:
  recipe-maintainers:
    - danielnachun
